# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='news.tags'),
        ),
    ]
