# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191001_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
