# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191002_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tags',
        ),
        migrations.AddField(
            model_name='articles',
            name='Tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
